In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error
import math

In [ ]:
df = pd.read_csv("/content/energydata_complete.csv")

In [ ]:
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [ ]:

#Select relevant columns (T2 and T6)
X = df[['T2']].values
y = df['T6'].values

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Fit a linear regression model
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Make predictions
y_pred = regressor.predict(X_test)

# Calculate RMSE
rmse = math.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error (RMSE): {:.3f}".format(rmse))

Root Mean Squared Error (RMSE): 3.620

In [ ]:
# Remove specified columns
data = df.drop(columns=['date', 'lights'])

In [ ]:
# Split the data into features (X) and target variable (y)
X = df.drop(columns=['Appliances'])
y = df['Appliances']

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

# Load the dataset
data = pd.read_csv('/content/energydata_complete.csv')

# Remove specified columns: "date" and "lights"
data = data.drop(columns=['date', 'lights'])

# Define the target variable ("Appliances")
y = data['Appliances']

# Define the features (independent variables) by excluding the target variable
X = data.drop(columns=['Appliances'])

# Split the data into training and test sets (70-30 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Normalize the data using MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Fit a multiple linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the training set
y_train_pred = model.predict(X_train)

# Calculate MAE for the training set
mae = mean_absolute_error(y_train, y_train_pred)

# Print the MAE
print("Mean Absolute Error (MAE) for the training set: {:.3f}".format(mae))

Mean Absolute Error (MAE) for the training set: 53.742

In [ ]:
# Calculate RMSE for the training set
rmse = mean_squared_error(y_train, y_train_pred, squared=False)
rmse

95.21565985214606

In [ ]:
# Make predictions on the test set
y_test_pred = model.predict(X_test)

# Calculate MAE for the test set
mae = mean_absolute_error(y_test, y_test_pred)

# Print the MAE with three decimal places
print("Mean Absolute Error (MAE) for the test set: {:.3f}".format(mae))

Mean Absolute Error (MAE) for the test set: 53.643